# Generated by Django 3.2.7 on 2021-09-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('cart', '0002_cart_produtc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
        migrations.DeleteModel(
            name='Cart_produtc',
        ),
    ]
